export const ADD_TO_CART = 'ADD_TO_CART';
export const CHANGE_MESSAGE = 'CHANGE_MESSAGE';
export const DELETE_PRODUCT_CART = 'DELETE_PRODUCT_CART';
export const UPDATE_PRODUCT_CART = 'UPDATE_PRODUCT_CART';